import { SEOPageData, commonFAQs } from '../shared';

export const templatePages: SEOPageData[] = [
    {
        slug: 'ai-flashcard-maker',
        title: 'AI Flashcard Maker',
        subtitle: 'Create Cards in Seconds',
        heroTitle: 'AI Flashcard Maker',
        heroSubtitle: 'Stop wasting hours making flashcards manually. Upload your notes, PDFs, or lectures and let AI create perfect study cards instantly.',
        description: 'The world\'s most powerful AI flashcard maker. Generate high-quality study cards from any material in seconds. Free for students.',
        keywords: [
            'ai flashcard maker', 'ai flashcard generator', 'automated flashcard creation', 'flashcard generator from pdf',
            'smart flashcards', 'ai study tool', 'flashcard maker free', 'create flashcards with ai',
            'intelligent flashcard maker', 'ai learning assistant', 'automatic study cards'
        ],
        features: [
            { title: 'Instant Generation', description: 'Convert PDFs and notes into flashcards in seconds using advanced AI.', icon: 'Zap' },
            { title: 'Smart Extraction', description: 'AI identifies key concepts and definitions automatically.', icon: 'Brain' },
            { title: 'Multi-Format Support', description: 'Upload PDFs, images, text, or even YouTube links.', icon: 'Files' },
            { title: 'Study Anywhere', description: 'Sync your flashcards across mobile and web platforms.', icon: 'Smartphone' }
        ],
        steps: [
            { number: '01', title: 'Upload Your Materials', description: 'Drop in your PDF, notes, or any study content' },
            { number: '02', title: 'AI Generates Cards', description: 'Our AI extracts key concepts and creates flashcards' },
            { number: '03', title: 'Start Studying', description: 'Review with spaced repetition for lasting memory' }
        ],
        faqs: [
            { question: 'How accurate is the AI flashcard generation?', answer: 'Our AI has a 95%+ accuracy rate in identifying key concepts. It understands context, so it doesn\'t just pull random sentences—it creates meaningful Q&A pairs.' },
            { question: 'Can I edit the generated flashcards?', answer: 'Yes! Every flashcard generated by AI is fully editable. You can tweak the wording, add images, or change the difficulty level.' },
            commonFAQs.isFree,
            commonFAQs.howItWorks,
            commonFAQs.fileSupport,
            { question: 'Does it support multiple languages?', answer: 'Yes, Masterly\'s AI flashcard maker works in over 50 languages, including Spanish, French, German, Chinese, and Hind.' },
            { question: 'How many flashcards can I generate?', answer: 'On the free plan, you can generate hundreds of flashcards per month. Pro users get unlimited generation and larger file uploads.' },
            commonFAQs.privacy,
            commonFAQs.devices,
            { question: 'Can I share flashcards with friends?', answer: 'Yes, you can easily share your AI-generated decks with classmates or study groups via a simple link.' }
        ],
        ctaTitle: 'Ready to Create Smarter Flashcards?',
        ctaSubtitle: 'Join thousands of students using AI to study more effectively.',
        testimonials: [
            { name: 'Sarah J.', role: 'Medical Student', content: 'This tool saved me 10 hours of manual typing every week. The quality of cards is better than what I make myself!', rating: 5 },
            { name: 'David M.', role: 'Law Student', content: 'Perfect for case law. I just upload my briefs and get instant active recall questions.', rating: 5 }
        ],
        relatedPages: ['pdf-to-flashcards', 'ai-quiz-generator', 'spaced-repetition']
    },
    {
        slug: 'pdf-to-flashcards',
        title: 'PDF to Flashcards',
        subtitle: 'Convert Documents Instantly',
        heroTitle: 'Convert PDF to Flashcards',
        heroSubtitle: 'Turn any textbook, research paper, or lecture slide PDF into a set of high-quality flashcards with one click.',
        description: 'The easiest way to convert PDF to flashcards. Our AI reads your documents and extracts the most important study material automatically.',
        keywords: [
            'pdf to flashcards', 'pdf flashcard converter', 'extract flashcards from pdf', 'textbook to flashcards',
            'pdf to anki', 'pdf to quizlet', 'automatic flashcard converter', 'pdf study tool'
        ],
        features: [
            { title: 'Bulk Processing', description: 'Handle large textbooks and lengthy documents with ease.', icon: 'Layers' },
            { title: 'Accuracy Guaranteed', description: 'Our AI understands context to create relevant questions.', icon: 'CheckCircle' },
            { title: 'Image Support', description: 'Even diagrams and tables can be converted into cards.', icon: 'Image' },
            { title: 'Instant Sync', description: 'Your new cards are ready on all your devices immediately.', icon: 'RefreshCw' }
        ],
        steps: [
            { number: '01', title: 'Upload PDF', description: 'Upload your textbook or notes in PDF format' },
            { number: '02', title: 'Select Pages', description: 'Choose the specific pages you want to study' },
            { number: '03', title: 'Get Flashcards', description: 'AI generates perfectly formatted active recall cards' }
        ],
        faqs: [
            { question: 'Is there a page limit for PDF uploads?', answer: 'The free tier supports PDFs up to 50 pages. Premium users can upload documents up to 500 pages long.' },
            { question: 'Can it handle scanned PDFs or handwriting?', answer: 'Yes! Our advanced OCR (Optical Character Recognition) can read scanned documents and even clear handwriting.' },
            commonFAQs.howItWorks,
            { question: 'Can I export the flashcards to Anki?', answer: 'Yes, you can export your cards to CSV or APKG format for use in Anki.' },
            { question: 'Does it work with complex diagrams?', answer: 'Our AI can analyze charts and diagrams, creating descriptive flashcards that help you understand visual material.' },
            { question: 'How long does the conversion take?', answer: 'Most PDFs are processed in less than 30 seconds. Large textbooks might take up to a minute.' },
            commonFAQs.isFree,
            commonFAQs.privacy,
            commonFAQs.devices,
            { question: 'Can I upload password-protected PDFs?', answer: 'For security reasons, we recommend removing the password before uploading, or you can paste the text directly into our "Notes to Flashcards" tool.' }
        ],
        ctaTitle: 'Turn Your PDFs into Grades',
        ctaSubtitle: 'Upload your first document now and see the magic.',
        testimonials: [
            { name: 'Michael R.', role: 'Engineering Student', content: 'I scanned my entire physics textbook and got high-quality cards in under a minute.', rating: 5 }
        ],
        relatedPages: ['ai-flashcard-maker', 'notes-to-flashcards', 'medical-school-study-app']
    },
    {
        slug: 'notes-to-flashcards',
        title: 'Notes to Flashcards',
        subtitle: 'Convert Notes Instantly',
        heroTitle: 'Turn Your Notes into Flashcards',
        heroSubtitle: 'Stop manually creating flashcards from your notes. Upload once, get perfect study cards in seconds with AI.',
        description: 'Easily convert notes to flashcards. Paste your text or upload your digital notes to create interactive study sets instantly with AI.',
        keywords: [
            'notes to flashcards', 'convert notes to flashcards', 'text to flashcards', 'handwritten notes to flashcards',
            'evernote to anki', 'notion to quizlet', 'automated card creation'
        ],
        features: [
            { title: 'Any Note Format', description: 'Works with typed notes, handwritten PDFs, or images.', icon: 'Files' },
            { title: 'Smart Parsing', description: 'AI understands your note structure and organization.', icon: 'Brain' },
            { title: 'Bulk Conversion', description: 'Convert entire notebooks or semesters of notes at once.', icon: 'Layers' },
            { title: 'Edit & Refine', description: 'Review and customize generated flashcards as needed.', icon: 'Wand2' }
        ],
        steps: [
            { number: '01', title: 'Upload Notes', description: 'Add your class notes in any format' },
            { number: '02', title: 'AI Converts', description: 'Watch as AI creates flashcards from key concepts' },
            { number: '03', title: 'Start Learning', description: 'Review with spaced repetition for maximum retention' }
        ],
        faqs: [
            { question: 'Can I paste text directly?', answer: 'Yes, you can either upload files or simply copy-paste your notes directly into our smart editor.' },
            { question: 'Does it work with Notion or Evernote?', answer: 'Yes, just export your notes as PDF or text and upload them. We are also working on direct integrations.' },
            { question: 'Can it read my messy handwriting?', answer: 'Our AI is quite robust at reading handwriting in images. For best results, ensure the lighting is good and the photo is clear.' },
            { question: 'What if my notes are just bullet points?', answer: 'Bullet points are actually great! Our AI understands hierarchical structures and turns them into logical question-and-answer pairs.' },
            { question: 'Can it generate summaries too?', answer: 'Yes, in addition to flashcards, Masterly can create concise summaries of long notes to help you see the "big picture".' },
            { question: 'How specific are the flashcards?', answer: 'You can control the depth. Choose "Comprehensive" for detail or "High-Yield" for just the most important facts.' },
            commonFAQs.howItWorks,
            commonFAQs.isFree,
            commonFAQs.privacy,
            commonFAQs.devices
        ],
        ctaTitle: 'Transform Your Notes Today',
        ctaSubtitle: 'Stop wasting time on manual flashcard creation.',
        relatedPages: ['ai-flashcard-maker', 'pdf-to-flashcards', 'ai-quiz-generator']
    },
    {
        slug: 'ai-quiz-generator',
        title: 'AI Quiz Generator',
        subtitle: 'Test Your Knowledge',
        heroTitle: 'AI-Powered Quiz Generator',
        heroSubtitle: 'Create unlimited practice quizzes from any study material. Perfect for self-testing and exam preparation.',
        description: 'The world\'s best AI quiz generator. Turn notes, PDFs, or lectures into custom practice tests with multiple-choice questions in seconds.',
        keywords: [
            'ai quiz generator', 'ai quiz maker', 'generate quiz from text', 'pdf to quiz',
            'multiple choice quiz generator', 'practice test maker', 'test yourself ai'
        ],
        features: [
            { title: 'Multiple Question Types', description: 'Multiple choice, true/false, short answer, and more.', icon: 'FileText' },
            { title: 'Difficulty Levels', description: 'Choose from easy, medium, or hard questions.', icon: 'Activity' },
            { title: 'Instant Grading', description: 'Get immediate feedback on your answers.', icon: 'CheckCircle' },
            { title: 'Unlimited Quizzes', description: 'Generate as many practice quizzes as you need.', icon: 'Repeat' }
        ],
        steps: [
            { number: '01', title: 'Upload Content', description: 'Add your study materials or textbook chapters' },
            { number: '02', title: 'Generate Quiz', description: 'AI creates a comprehensive quiz in seconds' },
            { number: '03', title: 'Take & Review', description: 'Test yourself and review detailed explanations' }
        ],
        faqs: [
            { question: 'Do the quizzes have explanations?', answer: 'Yes, every question comes with a detailed explanation of why the correct answer is right and why the other options are wrong.' },
            { question: 'What types of questions can it generate?', answer: 'We currently support Multiple Choice, True/False, Fill in the Blanks, and conceptual Short Answer questions.' },
            { question: 'How many questions can I have per quiz?', answer: 'You can choose to generate anywhere from 5 to 50 questions at a time.' },
            { question: 'Is it helpful for certifications like SAT or GRE?', answer: 'Absolutely. It\'s great for practicing the styles of questions found on standardized tests. Just upload a sample passage or chapter.' },
            { question: 'Can I export the quiz?', answer: 'Yes, you can export your practice tests as PDF or CSV for printing or using elsewhere.' },
            { question: 'Can I retake the same quiz?', answer: 'Yes, or you can have the AI generate a "Remix"—different questions covering the same core material from a different angle.' },
            commonFAQs.howItWorks,
            commonFAQs.isFree,
            commonFAQs.privacy,
            commonFAQs.devices
        ],
        ctaTitle: 'Start Creating Quizzes Now',
        ctaSubtitle: 'Test yourself with unlimited AI-generated practice questions.',
        relatedPages: ['exam-preparation-app', 'active-recall', 'ai-flashcard-maker']
    }
];
